# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DLvRD0zjWe65D1YkItuZS00Bin9jI7VJ
"""

l1 = ['sparshi','tarjani',('keyur',),'ritrisha',('rohan',)]
boys = sum(isinstance(l1,tuple) for l1 in l1)
girls = len(l1) - boys

print('boys: ',boys)
print('girls: ',girls)