# -*- coding: utf-8 -*-
"""Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O-Q2lk1vmYR8lCTUCAkCFf3IQ6jYDYXJ
"""

student = [(84,'sparshi',19),(87,'tarjani',18),(4,'jash',15)]
roll_no, names, age = zip(*student)

print(list(roll_no))
print(list(names))
print(list(age))