# -*- coding: utf-8 -*-
"""Q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFDZz0EyTL1ODjIg35fgWTkumqw1tepV
"""

from datetime import date
date1 = (16, 10,2024)
date2 = (23, 8, 2024)
d1 = date(*reversed(date1))
d2 = date(*reversed(date2))
tot_days = abs((d2-d1).days)

print('days in between = ', tot_days)