# -*- coding: utf-8 -*-
"""Q5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZAVmkbaA89205hMjhR1AZVfpW1elb9u
"""

l1 = [(1,3),(),(4,15),(3,8),(),(10,12)]
updated = [i for i in l1 if i]

print(updated)