# -*- coding: utf-8 -*-
"""Q6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1371ZrgM_08uL0YmpJGZ0440lW1tneaQd
"""

l = (2,4,6,8,10,12)
temp = list(l)
temp[1] = 44
l1 = tuple(temp)

print(l1)